export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const GOT_ALL_ARTICLES = "GOT_ALL_ARTICLES";
export const GOT_MY_ARTICLES = "GOT_MY_ARTICLES";
export const GOT_SINGLE_ARTICLE = "GOT_SINGLE_ARTICLE";
