//user-actions
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

//articles-actions
export const GOT_ALL_ARTICLES = "GOT_ALL_ARTICLES";
export const GOT_MY_ARTICLES = "GOT_MY_ARTICLES";
export const GOT_SINGLE_ARTICLE = "GOT_SINGLE_ARTICLE";
export const CLEAR_ARTICLES = "CLEAR_ARTICLES";

//comments-actions
export const GOT_ALL_COMMENTS = "GOT_ALL_COMMENTS";
export const GOT_MY_COMMENTS = "GOT_MY_COMMENTS";
export const GOT_COMMENTS_FOR_ARTICLE = "GOT_COMMENTS_FOR_ARTICLE";

//likes-actions
export const GOT_LIKES_FOR_ARTICLE = "GOT_LIKES_FOR_ARTICLE";
export const GOT_MY_LIKES = "GOT_MY_LIKES";

//search-actions
export const GOT_SEARCHED_ARTICLES = "GOT_SEARCHED_ARTICLES";
export const GETTING_SEARCHED_ARTICLES = "GETTING_SEARCHED_ARTICLES";
export const GOT_TAGGED_ARTICLES = "GOT_TAGGED_ARTICLES";
